### PR TITLE
Allow group admins/mods to unlink docs from group

### PR DESCRIPTION
**Pull request by dcavins**
Adds an “unlink from group” link on the group docs directory (visible to group admins and mods only). This request replaces an earlier attempt at this functionality. 

Here's a link to a patch of the changes in the pull request, because this history comparison looks ugly:
https://gist.github.com/dcavins/c91fc6f7d90617b495c6

Please let me know what else you'd like to see in this request.

Thanks!

### CODE REVIEW

**Comment by boonebgorges** [comment]
This is looking pretty good, @dcavins. I have a question about the reset-to-creator stuff. I wonder if this might be more fine-grained? I have a feeling it will confuse people if they unlink a public doc, and then find that it's invisible. Maybe the reset could be based on the current settings of the doc? Anything that is set to 'anyone' could be left alone.

**Comment by dcavins** [comment]
Yes, that wasn't well thought out. The new commit only changes the capability if it is group-related. 

See an updated diff:
https://gist.github.com/dcavins/06e2f8eb32bfa21513a5

I'm happy to make further changes pending your suggestions.

**Comment by boonebgorges** [comment]
Cool, this looks pretty good.

- Make sure you `return $links` when not in a group in 
`add_doc_action_unlink_from_group_link()` - now you're returning null, 
and breaking links on the main directory.
- Check for trailing whitespace :)
- Would you mind writing a unit test for the new mapped cap?

**Comment by dcavins** [comment]
Ha ha, your comments made me think there was a whitespace epidemic. OK, there was more than one. :)

Thanks for your feedback. I've fixed the all-consuming filter and the offending whitespaces. A test on the `map_meta_cap` filter will follow.

**Comment by dcavins** [comment]
Boone-
The one case in the `map_meta_cap` I couldn't figure out how to test is if the `current_user_can` happens in the loop and the `group_id` isn't sent as an argument--the fallback case here:
```
if ( isset( $args[0] ) ) {
				$group_id = intval( $args[0] );
			} elseif ( bp_is_group() ) {
				$group_id = bp_get_current_group_id();
			} else {
				$group_id = bp_docs_get_associated_group_id( get_the_ID() );
			}
``` 
I'm sending the `group_id` as an argument where I'm using it, but tried to write tests to cover less-than-ideal uses of the function. Let me know if you have a good idea for other bad ideas I should be testing against.

Thanks!

**Comment by boonebgorges** [comment]
> I couldn't figure out how to test is if the current_user_can happens in the loop and the group_id isn't sent as an argument

Isn't that what you're testing here? https://github.com/dcavins/buddypress-docs/commit/bf22affb65177db42a8283b7ad0f0477d5e63b52#diff-9839a4cca13517ceed05f77e732f2f80R1104

Tests are looking good, I think.

**Comment by dcavins** [comment]
Yes, I think so. Not super explicitly. But yes. The tests cover more cases than the change in the code attempts, but I was trying to find the weird edge cases. If the tests satisfy you, then I'm satisfied. :)

**Comment by boonebgorges** [comment]
Let's do it. Thanks, @dcavins.

**Pull request merged**
