### PR TITLE
Remove doc from group

### PR DESCRIPTION
**Pull request by dcavins**
Only site admins (users with ‘bp_moderate’ cap) and the doc owner can
change group association. This patch proposes a checkbox for removing a
specific group association from a doc. There is still a problem of a
redirect issue after save—the editing user no longer has access to the
doc, but is redirected to it, resulting in a bp_noaccess.

Please offer any feedback on the proposed patch. I'll add a test later, once you let me know that you think this approach will work.

Thanks!

### CODE REVIEW

**Comment by boonebgorges** [comment]
Hi @dcavins - Sorry for the delay in getting to this. It's definitely a problem that group admins/mods can't remove Doc association from a group.

Your suggested solution involves a checkbox on the Edit page. I'm having a hard time making this work - when, as a group admin, I try to edit a doc associated with a group I own (but to which I don't have the Edit permission), I don't see the Edit link, and I get bounced from the Edit page. I assume this is a modest bug that could be easily fixed.

Regardless, I wonder if allowing access to the Edit page just for this purpose is more trouble than its worth. What do you think of something like this: In the "associated group summary" - the group label/avatar that appears just below the Doc title - there is a link that says "Unlink from group" or something like that? One click (maybe with a confirm dialog). No messing with the Edit page. What do you think?

**Comment by dcavins** [comment]
Oops, I didn't remember that case of "only owner can edit but is associated with a group". You're absolutely right.

My original thought was that all edit-like actions should happen on the edit page since that's where'd you delete attachments or delete the doc itself, but I agree that offering that action on the doc list table would cover every case, and would be maybe more obvious for group admins.

In the group library view, there's no "associated group summary" column, but you could add the action to the other actions, like Read | Edit | History | Unlink from Group:
docs-group-library

I'm not sure that it's totally necessary to be able to remove docs from a group when not in the group. I guess that would be nice-to-have for some users, but I'd be OK with that action only happening from within the group context.

Thanks very much for taking a look at this. If it would be helpful, I could take a run at a patch in this direction, but only if that would actually be helpful to you.

**Comment by boonebgorges** [comment]
> In the group library view, there's no "associated group summary" column, but you could add the action to the other actions, like Read | Edit | History | Unlink from Group

This sounds like a great solution. Yes, let's only make it available when on the group's `/docs` page.

**Comment by dcavins** [comment]
Superseded by #444.

**Pull request closed without merging**
