### PR TITLE
Docs edit add actions

### PR DESCRIPTION
**Pull request by dcavins**
Hi Boone-

Here's a request for action points in the meta area of the doc edit screen. (I'm adding another taxonomy for docs and need a place to put it.)

Thanks,

David

### CODE REVIEW

**Comment by boonebgorges** [comment]
:+1:

**Comment by dcavins** [comment]
Hi Boone-

I didn't realize that you'd already added some action points in the edit metabox for the 1.9.x branch. I can use those instead. Can we add the current doc ID to them as an argument to pass?

https://github.com/boonebgorges/buddypress-docs/blob/1.9.x/includes/templates/docs/single/edit.php

Thanks!

**Comment by boonebgorges** [comment]
Yeah, can you assemble a PR for that branch? (You can eliminate the 
hooks from the previous one if you want.)

**Comment by dcavins** [comment]
Yep. Which action name style would you like me to use?
`bp_docs_after_tags_meta_box` vs `bp_docs_doc_edit_metabox_after_tags`

**Comment by boonebgorges** [comment]
First one sounds marginally more natural, though then it'll mean that 
the modifier (tags vs other metaboxes) will be in the middle rather than 
the end of the hook name. I guess I prefer the first one, but I don't 
have strong feelings.

**Comment by dcavins** [comment]
Would you prefer to use `get_the_ID()` several times and hope for cache hits or would you rather I initialize a variable to persist through the template?

**Comment by boonebgorges** [comment]
Init the variable once. Less about cache hits (the cache will be hit no 
matter what) and more about not running the same set of filters more 
than once.

**Pull request merged**
