### PR TITLE
Attachment filter fixes

### LINKED ISSUE #472: Directory - Browse by attachment status bypasses access protection
In the directory, if browsing by "has attachment" status (eg. at the endpoint `/docs/?has-attachment=yes`), private docs are shown in the results.  You can't access the individual docs but you can see the 'blurb' which may contain sensitive information.

This seems to be because the post type with the has-attachment url param switches the post type being queried to "attachment" as opposed to "bp_doc".

I've worked around it in the meantime by altering a few lines in the access-query.php but they aren't fit for a PR, so I'm leaving this here.

### PR DESCRIPTION
**Pull request by christianwach**
You may well have a better solution to this @boonebgorges but these two commits fix #472 for me.

### CODE REVIEW

**Comment by boonebgorges** [comment]
Thanks, @christianwach. I think this will work.

**Comment by christianwach** [comment]
@boonebgorges Would you prefer a separate PR for 57f839d3389d19806c8d7801065557065eab3399?

**Comment by boonebgorges** [comment]
@christianwach It was merged: f826960b

**Comment by christianwach** [comment]
@boonebgorges Ah, I see - you committed https://github.com/boonebgorges/buddypress-docs/pull/540/commits/512d54b306d4cf2b94928f8a06f12b206c0ca2e3 separately. GitHub usually asks me if I want to delete the branch that the PR was based on otherwise. Thanks for the commits!

**Pull request closed without merging**
