### PR TITLE
'Save and Continue Editing' button.

### PR DESCRIPTION
**Pull request by boonebgorges**
See #67.

@dcavins Could you have a look at this? It clutters up the interface a tad but I think it's a valuable addition.

Also, please sign off on the new `redirect_to` param for the `save()` method. It's a bit clunky, but I couldn't think of a better way to do it without tearing the whole thing apart.

### CODE REVIEW

**Comment by dcavins** [comment]
@boonebgorges This change looks good to me, and I agree that it's a useful change. 

I wonder if maybe we could (in the future) make the save button have alternate actions (sort of like github does, I think) where the primary action "Save" is shown, and part of the button is a dropdown indicator for less-often-used variants. Like: [ Save | v ]. Similarly, the other actions are just listed out, maybe they could be gathered up in a select kind of like the bulk actions in the WP posts admin.

[ Cancel or Delete | v  ]  [ Apply ]
[ Cancel                           ]
[ Move to Trash             ]
[ Permanently Delete ]

I'm always doubtful about hiding options/actions, but if the groups were sensible, maybe it would be helpful. (Also the select > apply two-step is kind of a nice way to avoid accidentally doing something without a popup.) Maybe we should explore some edit interface updates for 2.1?

Thanks!

**Comment by boonebgorges** [comment]
Love that idea - I'll open a ticket.

**Comment by dcavins** [comment]
Boo. When I accepted this merge, it got merged into `master` which was probably not the desired result. Sorry that I can't use web technology.

**Comment by boonebgorges** [comment]
It's my fault for doing a PR against master. I'll fix it.

**Pull request merged**
